# Generated by Django 3.2.7 on 2021-09-06 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(validators=[django.core.validators.MaxValueValidator(28), django.core.validators.MinValueValidator(19)])),
                ('humidity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(65), django.core.validators.MinValueValidator(35)])),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
